### PR TITLE
Fix mocha

### PR DESCRIPTION
**Pull request by ali2251**
Major update to the structure of the repo and improved testing

### CODE REVIEW

**Comment by ali2251** [comment]
should squash and merge!

**Comment by yahgwai** [comment]
This looks great. I'm ready to merge, but why does it update files in the statechannels repo?

**Comment by ali2251** [comment]
@yahgwai it moved state channel repo out to root of the directory, so git shows that as an add/delete

**Comment by yahgwai** [comment]
But they shouldnt be committed right? The submodule should stop that from happening. We should just have the root folder committed I think.

**Pull request merged**
